<?php

namespace bot\session;
use kaiheila\api\base\WebsocketSession;

class WebSocket extends WebsocketSession
{
    public function start()
    {
        \Co\run(function () {
            parent::start(); // TODO: Change the autogenerated stub
        });
    }
}